okta/okta-aspnet

Okta.AspNet.sln
Okta.AspNet/Okta.AspNet.csproj
Okta.AspNet/OktaMiddlewareExtensions.cs
Okta.AspNetCore/Okta.AspNetCore.csproj
Okta.AspNetCore/OktaAuthenticationOptionsExtensions.cs

Add support for self-hosted login page.

---

Okta.AspNet.Abstractions/Okta.AspNet.Abstractions.csproj
Okta.AspNet/Okta.AspNet.csproj
Okta.AspNetCore/Okta.AspNetCore.csproj

See version details: https://github.com/okta/okta-aspnet/releases/tag/1.1.1

Bump project version.

---

Okta.AspNet.Abstractions/Okta.AspNet.Abstractions.csproj
Okta.AspNet/Okta.AspNet.csproj
Okta.AspNetCore/Okta.AspNetCore.csproj

Bump Abstractions to 3.0.0.
Bump Asp.Net and Asp.NetCore to 1.1.3.

Bump project versions.

---

Okta.AspNet.Abstractions/Okta.AspNet.Abstractions.csproj
Okta.AspNet/Okta.AspNet.csproj
Okta.AspNetCore/Okta.AspNetCore.csproj

Abstractions -> 2.0.0
Asp.Net and Asp.NetCore -> 1.1.2

Fix project versions

---

Okta.AspNet.Abstractions/Okta.AspNet.Abstractions.csproj
Okta.AspNet/Okta.AspNet.csproj
Okta.AspNetCore/Okta.AspNetCore.csproj

Abstractions:  3.0.0 (Added new classes)
Asp.Net/Asp.NetCore: 1.1.3 (Enforce JWT token's alg validation).

Bump projects version

---

Okta.AspNet.Abstractions/Okta.AspNet.Abstractions.csproj
Okta.AspNet/Okta.AspNet.csproj
Okta.AspNet/TokenExchanger.cs
Okta.AspNetCore/Okta.AspNetCore.csproj

Fixes [OKTA-205915](https://oktainc.atlassian.net/browse/OKTA-205915).
This is fixed by updating the `IdentityModel` package to the last version.

 Runtime error with identitymodel

---

Okta.AspNet.Abstractions/Okta.AspNet.Abstractions.csproj
Okta.AspNet/Okta.AspNet.csproj
Okta.AspNetCore/Okta.AspNetCore.csproj

Okta.AspNet 1.1.4
Okta.AspNetCore 1.1.4
Okta.AspNet.Abstractions 3.0.1

Bump project version

---

Okta.AspNet.Test/OpenIdConnectAuthenticationOptionsBuilderShould.cs
Okta.AspNet/OktaMiddlewareExtensions.cs
Okta.AspNet/OpenIdConnectAuthenticationOptionsBuilder.cs
Okta.AspNetCore.Test/OpenIdConnectOptionsHelperShould.cs
Okta.AspNetCore/OktaAuthenticationOptionsExtensions.cs
Okta.AspNetCore/OktaMvcOptions.cs
Okta.AspNetCore/OpenIdConnectOptionsHelper.cs

Add PostLogoutRedirectUri property in the OktaMvcOptions Class (Core)

---

Okta.AspNet/Okta.AspNet.csproj
Okta.AspNetCore/Okta.AspNetCore.csproj

Update Asp.Net packages version to 1.1.5

---

docs/aspnet4x-mvc.md
docs/aspnet4x-webapi.md

Add troubleshooting section in readme for ASP.NET 4.x.

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

Also, I've updated the README to reference the CONTRIBUTING guide.

Add CONTRIBUTING and CODE OF CONDUCT files.

---

Okta.AspNet.Abstractions/Okta.AspNet.Abstractions.csproj
Okta.AspNet/Okta.AspNet.csproj
Okta.AspNetCore/Okta.AspNetCore.csproj
docs/aspnet4x-mvc.md
docs/aspnetcore-mvc.md

Versions:
* `Okta.AspNet.Abstractions` from `3.0.1` -> `3.0.2` - Comments/Doc were added to some public properties
* `Okta.AspNet` from `1.1.6` -> `1.2.0` - Deprecated property / New feature - No breaking changes
* `Okta.AspNet.Core` from `1.1.5` -> `1.2.0` - New features - No breaking changes
This is gonna be merged after #83.

Update projects versions and readme files.

---

Okta.AspNet/Okta.AspNet.csproj

This version includes #89 .
Asp.Net Core & Asp.Net Abstractions have no changes.

Bump Asp.Net version to 1.3.0.

---

README.md
docs/aspnet4x-mvc.md
docs/aspnetcore-mvc.md

* Update project's readme to include guides.
* Update ASP.NET Core docs with self-hosted login configuration samples.

Update docs files.

---

Okta.AspNet/OktaMiddlewareExtensions.cs
Okta.AspNetCore.Mvc.IntegrationTest/Controllers/AccountController.cs
Okta.AspNetCore.Mvc.IntegrationTest/MiddlewareShould.cs
Okta.AspNetCore/OktaAuthenticationOptionsExtensions.cs
docs/aspnet4x-mvc.md
docs/aspnetcore-mvc.md

* Allow passing an IdP id in the authorize URL.
* Fixes OKTA-245677

Add support for social login.

---

Okta.AspNet/Okta.AspNet.csproj
Okta.AspNetCore/Okta.AspNetCore.csproj

* Asp.Net from 1.3.0 to 1.4.0
* Asp.NetCore from 1.2.0 to 1.3.0
This release includes:
* Added support for external identity providers (OKTA-245677)

Update project versions

---

Okta.AspNet.Abstractions/OktaWebApiOptionsValidator.cs
Okta.AspNet.Test/OktaWebApiOptionsValidatorShould.cs
docs/aspnet4x-mvc.md
docs/aspnet4x-webapi.md
docs/aspnetcore-mvc.md
docs/aspnetcore-webapi.md

* Throw when the Org AS is configured to be used in Web API projects.
* Add more details in our README of what scenarios we do/don't support when using the Org AS.
* Fixes OKTA-307680
OKTA-307680

Clarifying support for the Org Autorization Server

---

docs/aspnet4x-mvc.md
docs/aspnetcore-mvc.md

Add example of accessing OIDC tokens to README files.

OKTA-254845: document how to access OIDC tokens

---

Okta.AspNet/Okta.AspNet.csproj

Update Okta.AspNet Version to 1.6.0

---

Okta.AspNet.Abstractions/CHANGELOG.md
Okta.AspNet.Abstractions/Okta.AspNet.Abstractions.csproj
Okta.AspNet/CHANGELOG.md
Okta.AspNet/Okta.AspNet.csproj
Okta.AspNetCore/CHANGELOG.md
Okta.AspNetCore/Okta.AspNetCore.csproj

* Okta.AspNet.Abstractions changed from `3.0.5` to `3.1.0`
* Okta.AspNet changed from `1.6.0` to `1.7.0`
* Okta.AspNetCore changed from `3.2.0` to `3.3.0`
These new packages will include support for WebProxy.

Update projects' version and changelogs.

---

Okta.AspNet.Abstractions.Test/UserAgentHelperShould.cs
Okta.AspNet.Abstractions/UserAgentBuilder.cs
Okta.AspNet.Abstractions/UserAgentHelper.cs

This PR includes https://github.com/okta/okta-aspnet/pull/146 which was already reviewed and approved by the team.
Fix #146

Andriizhegurov OKTA-276823 ASP.NET > Trigger Travis

---

Okta.AspNet.Abstractions/OktaParams.cs
Okta.AspNet.Test/OktaHttpMessageHandlerShould.cs
Okta.AspNet.sln
Okta.AspNet/OktaMvcOptions.cs
Okta.AspNet/OpenIdConnectAuthenticationOptionsBuilder.cs
Okta.AspNetCore.Mvc.IntegrationTest/Controllers/AccountController.cs
Okta.AspNetCore.Mvc.IntegrationTest/OktaMiddlewareShould.cs
Okta.AspNetCore.Test/OktaHttpMessageHandlerShould.cs
Okta.AspNetCore/OktaAuthenticationOptionsExtensions.cs
docs/aspnet4x-mvc.md
docs/aspnetcore-mvc.md

* Add support for login_hint
* Refactor existing code to make it easier to add support for other Okta params in the future
* Update Readme with usage examples
* Fix old StyleCop issues.
Fix #142 
Fix OKTA-326154

Add support for login_hint param

---

docs/aspnetcore-mvc.md

https://oktainc.atlassian.net/browse/OKTA-346990
Added info on deployment to Cloud Services for Asp.Net Core

OKTA-346990 update readme(s) to include extended configuration information

---

docs/aspnet4x-mvc.md
docs/aspnetcore-mvc.md

Clarify in readme how to configure Okta when using the Org Authz Server.
Fix OKTA-362091

Fix OKTA-362091.

---

README.md
docs/refresh-token.md

Initial commit

---

Okta.AspNet.Abstractions/CHANGELOG.md
Okta.AspNet.Abstractions/Okta.AspNet.Abstractions.csproj
Okta.AspNet/CHANGELOG.md
Okta.AspNet/Okta.AspNet.csproj
build.cake

Add NoBuild option for PackNuget action to preserve pre-applied strong names

Add NoBuild option for PackNuget build action to preserve strongnames

---

Okta.AspNet.Abstractions/OktaWebOptions.cs
Okta.AspNet.Test/Okta.AspNet.Test.csproj
Okta.AspNet.Test/OpenIdConnectAuthenticationOptionsBuilderShould.cs
Okta.AspNet.WebApi.IntegrationTest/MiddlewareShould.cs
Okta.AspNet.WebApi.IntegrationTest/Okta.AspNet.WebApi.IntegrationTest.csproj
Okta.AspNet.WebApi.IntegrationTest/Startup.cs
Okta.AspNet.WebApi.IntegrationTest/Web.config
Okta.AspNet.WebApi.IntegrationTest/packages.config
Okta.AspNet/OktaMiddlewareExtensions.cs
Okta.AspNet/OktaMvcOptions.cs
Okta.AspNet/OktaWebApiOptions.cs
Okta.AspNet/OpenIdConnectAuthenticationOptionsBuilder.cs
Okta.AspNetCore.Mvc.IntegrationTest/OktaMiddlewareShould.cs
Okta.AspNetCore.Mvc.IntegrationTest/Startup.cs
Okta.AspNetCore.Test/Okta.AspNetCore.Test.csproj
Okta.AspNetCore.Test/OpenIdConnectOptionsHelperShould.cs
Okta.AspNetCore.WebApi.IntegrationTest/OktaMiddlewareShould.cs
Okta.AspNetCore.WebApi.IntegrationTest/Startup.cs
Okta.AspNetCore/OktaAuthenticationOptionsExtensions.cs
Okta.AspNetCore/OktaMvcOptions.cs
Okta.AspNetCore/OktaWebApiOptions.cs
Okta.AspNetCore/OpenIdConnectOptionsHelper.cs
README.md
docs/aspnet4x-mvc.md
docs/aspnet4x-webapi.md
docs/aspnetcore-mvc.md
docs/aspnetcore-webapi.md

Expose OIDC events for .NET 4.x and Core MVC projects.
Expose JWT events for .NET 4.x and Core WebApi projects.
Add tests.
Update readme.

Expose OIDC and JWT events

---

README.md
docs/refresh-token-aspnetcore.md

OKTA-433769 ASP.NET Core > Provide Refresh Token code sample in ASP.NET Core
Added a code sample for refresh access token for Asp.Net Core App. The sample is taken from https://newbedev.com/handling-expired-refresh-tokens-in-asp-net-core, simplified for clarity and adapted to be used in one of the Okta aspnetcore sample projects.

Provide refresh token code sample

---

build.sh

Use https to download files

---

Okta.AspNet.Abstractions.Test/Okta.AspNet.Abstractions.Test.csproj
Okta.AspNet.Abstractions/Okta.AspNet.Abstractions.csproj
Okta.AspNet.Test/JwtOptionsBuilderShould.cs
Okta.AspNet.Test/Okta.AspNet.Test.csproj
Okta.AspNet.Test/OpenIdConnectAuthenticationOptionsBuilderShould.cs
Okta.AspNet.WebApi.IntegrationTest/MiddlewareWithCustomAuthTypeShould.cs
Okta.AspNet.WebApi.IntegrationTest/Okta.AspNet.WebApi.IntegrationTest.csproj
Okta.AspNet.WebApi.IntegrationTest/StartupWithCustomAuthType.cs
Okta.AspNet.WebApi.IntegrationTest/Web.config
Okta.AspNet.WebApi.IntegrationTest/packages.config
Okta.AspNet/CHANGELOG.md
Okta.AspNet/JwtOptionsBuilder.cs
Okta.AspNet/Okta.AspNet.csproj
Okta.AspNet/OktaMiddlewareExtensions.cs
Okta.AspNet/OpenIdConnectAuthenticationOptionsBuilder.cs
Okta.AspNetCore.Mvc.IntegrationTest/Okta.AspNetCore.Mvc.IntegrationTest.csproj
Okta.AspNetCore.Test/Okta.AspNetCore.Test.csproj
Okta.AspNetCore.WebApi.IntegrationTest/Okta.AspNetCore.WebApi.IntegrationTest.csproj
docs/aspnet4x-mvc.md
docs/aspnet4x-webapi.md

Add support for authentication type configuration.

Port 3rd party contribution to ASP.NET (#191)

---

Okta.AspNet.Abstractions/CHANGELOG.md
Okta.AspNet.Abstractions/Okta.AspNet.Abstractions.csproj

- Update `Microsoft.IdentityModel.Tokens` dependency to `6.17.0`
- Update `System.IdentityModel.Tokens.Jwt` dependency to `6.17.0`
- Fix #212

Update project's version and changelog.

---

global.json

This fixes internal build issue.

Update global json file to use .NET 6.0.101

---

Okta.AspNet.Abstractions/CHANGELOG.md
Okta.AspNet.Abstractions/Okta.AspNet.Abstractions.csproj
Okta.AspNet.WebApi.IntegrationTest/Web.config
Okta.AspNet.WebApi.IntegrationTest/packages.config
Okta.AspNet/Okta.AspNet.csproj
README.md

- Updated target framework 4.6.2 where appropriate.

OKTA-576349: update target framework to 4.6.2 where appropriate

---

Okta.AspNetCore.Mvc.IntegrationTest/Okta.AspNetCore.Mvc.IntegrationTest.csproj
Okta.AspNetCore.Test/Okta.AspNetCore.Test.csproj
Okta.AspNetCore.WebApi.IntegrationTest/Okta.AspNetCore.WebApi.IntegrationTest.csproj
Okta.AspNetCore/CHANGELOG.md
Okta.AspNetCore/Okta.AspNetCore.csproj
README.md

* Added net7 target
* Updates test projects to also target net7
* Update Readme and changelog

Add support for .NET 7

---

Okta.AspNet/CHANGELOG.md
Okta.AspNet/DiscoveryDocumentCachingSigningKeyProvider.cs
Okta.AspNet/Okta.AspNet.csproj

Introduce 3rd party's contribution and prepare patch release 

---

Okta.AspNetCore.Mvc.IntegrationTest/Okta.AspNetCore.Mvc.IntegrationTest.csproj
Okta.AspNetCore.Test/Okta.AspNetCore.Test.csproj
Okta.AspNetCore.WebApi.IntegrationTest/Okta.AspNetCore.WebApi.IntegrationTest.csproj
Okta.AspNetCore/CHANGELOG.md
Okta.AspNetCore/Okta.AspNetCore.csproj
Okta.AspNetCore/OktaAuthenticationOptionsExtensions.cs
Okta.AspNetCore/OpenIdConnectOptionsHelper.cs
README.md

Test 3rd Party PR: Add support for .NET 8

---

.circleci/config.yml
Okta.AspNet.WebApi.IntegrationTest/MockHttpMessageHandler.cs
Okta.AspNet.WebApi.IntegrationTest/Okta.AspNet.WebApi.IntegrationTest.csproj
Okta.AspNet.WebApi.IntegrationTest/packages.config
docs/aspnet4x-webapi.md

Update WebApi 4.x docs to fix runtime exception

---

Okta.AspNet.Abstractions/CHANGELOG.md
Okta.AspNet.Abstractions/Okta.AspNet.Abstractions.csproj
Okta.AspNet/CHANGELOG.md
Okta.AspNet/Okta.AspNet.csproj
Okta.AspNetCore/CHANGELOG.md
Okta.AspNetCore/Okta.AspNetCore.csproj

This pull request is an addition to the https://github.com/okta/okta-aspnet/pull/275 to update the versions.
Update project's version:
- Okta.AspNet.Abstractions from 5.1.0 to 5.1.1.
- Okta.AspNet from 3.2.4 to 3.2.5.
- Okta.AspNetCore from 4.6.1 to 4.6.2.
- Add changelogs

Prepare release

---

.circleci/config.yml

Adds malware scanner (Reversing Labs) and, Semgrep job, and fixes snyk scan; cleans redundant steps.

chore: integrate malware scanner and semgrep, and fix snyk scan
